# This patch file was generated by NetBeans IDE
# It uses platform neutral UTF-8 encoding and \n newlines.
--- a/app/Providers/RepositoryServiceProvider.php
+++ b/app/Providers/RepositoryServiceProvider.php
@@ -8,19 +8,38 @@
 
     namespace App\Providers;
     use Illuminate\Support\ServiceProvider;
+    use App\Repositories\Contracts\InfoRepositoryBackend;
+    use App\Repositories\Eloquent\EloquentInfoBackend;
     use App\Repositories\Contracts\AutoRepositoryBackend;
     use App\Repositories\Eloquent\EloquentAutoBackend;
     use App\Repositories\Contracts\HotelRepository;
     use App\Repositories\Eloquent\EloquentHotel;
+
     use App\Repositories\Contracts\PlanningRepository;
     use App\Repositories\Eloquent\EloquentPlanning;
 
+    
+    use App\Repositories\Contracts\VervoerRepositoryBackend;
+    use App\Repositories\Eloquent\EloquentVervoerBackend;
+    
+    use App\Repositories\Contracts\AutoRepository;
+    use App\Repositories\Eloquent\EloquentAuto;
+
+
     class RepositoryServiceProvider extends ServiceProvider
     {
         public function register()
         {
+            $this->app->singleton(InfoRepositoryBackend::class, EloquentInfoBackend::class);
             $this->app->singleton(AutoRepositoryBackend::class, EloquentAutoBackend::class);
             $this->app->singleton(HotelRepository::class, EloquentHotel::class);
+
             $this->app->singleton(PlanningRepository::class, EloquentPlanning::class);
+
+            
+            $this->app->singleton(VervoerRepositoryBackend::class, EloquentVervoerBackend::class);
+            $this->app->singleton(AutoRepository::class, EloquentAuto::class);
+
         }
     }
+
